#############################################################################
# Makefile for building: cass
# Generated by qmake (2.01a) (Qt 4.5.3) on: Wed Dec 9 08:22:41 2009
# Project:  cass.pro
# Template: subdirs
# Command: /usr/bin/qmake -unix -o Makefile cass.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-cass_remi \
		sub-cass_vmi \
		sub-cass_pnccd \
		sub-cass_machinedata \
		sub-cass

cass_remi//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) cass_remi/ || $(MKDIR) cass_remi/ 
	cd cass_remi/ && $(QMAKE) cass_remi.pro -unix -o $(MAKEFILE)
sub-cass_remi-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) cass_remi/ || $(MKDIR) cass_remi/ 
	cd cass_remi/ && $(QMAKE) cass_remi.pro -unix -o $(MAKEFILE)
sub-cass_remi: cass_remi//$(MAKEFILE) FORCE
	cd cass_remi/ && $(MAKE) -f $(MAKEFILE)
sub-cass_remi-make_default: cass_remi//$(MAKEFILE) FORCE
	cd cass_remi/ && $(MAKE) -f $(MAKEFILE) 
sub-cass_remi-make_first: cass_remi//$(MAKEFILE) FORCE
	cd cass_remi/ && $(MAKE) -f $(MAKEFILE) first
sub-cass_remi-all: cass_remi//$(MAKEFILE) FORCE
	cd cass_remi/ && $(MAKE) -f $(MAKEFILE) all
sub-cass_remi-clean: cass_remi//$(MAKEFILE) FORCE
	cd cass_remi/ && $(MAKE) -f $(MAKEFILE) clean
sub-cass_remi-distclean: cass_remi//$(MAKEFILE) FORCE
	cd cass_remi/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cass_remi-install_subtargets: cass_remi//$(MAKEFILE) FORCE
	cd cass_remi/ && $(MAKE) -f $(MAKEFILE) install
sub-cass_remi-uninstall_subtargets: cass_remi//$(MAKEFILE) FORCE
	cd cass_remi/ && $(MAKE) -f $(MAKEFILE) uninstall
cass_vmi//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) cass_vmi/ || $(MKDIR) cass_vmi/ 
	cd cass_vmi/ && $(QMAKE) cass_vmi.pro -unix -o $(MAKEFILE)
sub-cass_vmi-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) cass_vmi/ || $(MKDIR) cass_vmi/ 
	cd cass_vmi/ && $(QMAKE) cass_vmi.pro -unix -o $(MAKEFILE)
sub-cass_vmi: cass_vmi//$(MAKEFILE) FORCE
	cd cass_vmi/ && $(MAKE) -f $(MAKEFILE)
sub-cass_vmi-make_default: cass_vmi//$(MAKEFILE) FORCE
	cd cass_vmi/ && $(MAKE) -f $(MAKEFILE) 
sub-cass_vmi-make_first: cass_vmi//$(MAKEFILE) FORCE
	cd cass_vmi/ && $(MAKE) -f $(MAKEFILE) first
sub-cass_vmi-all: cass_vmi//$(MAKEFILE) FORCE
	cd cass_vmi/ && $(MAKE) -f $(MAKEFILE) all
sub-cass_vmi-clean: cass_vmi//$(MAKEFILE) FORCE
	cd cass_vmi/ && $(MAKE) -f $(MAKEFILE) clean
sub-cass_vmi-distclean: cass_vmi//$(MAKEFILE) FORCE
	cd cass_vmi/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cass_vmi-install_subtargets: cass_vmi//$(MAKEFILE) FORCE
	cd cass_vmi/ && $(MAKE) -f $(MAKEFILE) install
sub-cass_vmi-uninstall_subtargets: cass_vmi//$(MAKEFILE) FORCE
	cd cass_vmi/ && $(MAKE) -f $(MAKEFILE) uninstall
cass_pnccd//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) cass_pnccd/ || $(MKDIR) cass_pnccd/ 
	cd cass_pnccd/ && $(QMAKE) cass_pnccd.pro -unix -o $(MAKEFILE)
sub-cass_pnccd-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) cass_pnccd/ || $(MKDIR) cass_pnccd/ 
	cd cass_pnccd/ && $(QMAKE) cass_pnccd.pro -unix -o $(MAKEFILE)
sub-cass_pnccd: cass_pnccd//$(MAKEFILE) FORCE
	cd cass_pnccd/ && $(MAKE) -f $(MAKEFILE)
sub-cass_pnccd-make_default: cass_pnccd//$(MAKEFILE) FORCE
	cd cass_pnccd/ && $(MAKE) -f $(MAKEFILE) 
sub-cass_pnccd-make_first: cass_pnccd//$(MAKEFILE) FORCE
	cd cass_pnccd/ && $(MAKE) -f $(MAKEFILE) first
sub-cass_pnccd-all: cass_pnccd//$(MAKEFILE) FORCE
	cd cass_pnccd/ && $(MAKE) -f $(MAKEFILE) all
sub-cass_pnccd-clean: cass_pnccd//$(MAKEFILE) FORCE
	cd cass_pnccd/ && $(MAKE) -f $(MAKEFILE) clean
sub-cass_pnccd-distclean: cass_pnccd//$(MAKEFILE) FORCE
	cd cass_pnccd/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cass_pnccd-install_subtargets: cass_pnccd//$(MAKEFILE) FORCE
	cd cass_pnccd/ && $(MAKE) -f $(MAKEFILE) install
sub-cass_pnccd-uninstall_subtargets: cass_pnccd//$(MAKEFILE) FORCE
	cd cass_pnccd/ && $(MAKE) -f $(MAKEFILE) uninstall
cass_machinedata//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) cass_machinedata/ || $(MKDIR) cass_machinedata/ 
	cd cass_machinedata/ && $(QMAKE) cass_machinedata.pro -unix -o $(MAKEFILE)
sub-cass_machinedata-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) cass_machinedata/ || $(MKDIR) cass_machinedata/ 
	cd cass_machinedata/ && $(QMAKE) cass_machinedata.pro -unix -o $(MAKEFILE)
sub-cass_machinedata: cass_machinedata//$(MAKEFILE) FORCE
	cd cass_machinedata/ && $(MAKE) -f $(MAKEFILE)
sub-cass_machinedata-make_default: cass_machinedata//$(MAKEFILE) FORCE
	cd cass_machinedata/ && $(MAKE) -f $(MAKEFILE) 
sub-cass_machinedata-make_first: cass_machinedata//$(MAKEFILE) FORCE
	cd cass_machinedata/ && $(MAKE) -f $(MAKEFILE) first
sub-cass_machinedata-all: cass_machinedata//$(MAKEFILE) FORCE
	cd cass_machinedata/ && $(MAKE) -f $(MAKEFILE) all
sub-cass_machinedata-clean: cass_machinedata//$(MAKEFILE) FORCE
	cd cass_machinedata/ && $(MAKE) -f $(MAKEFILE) clean
sub-cass_machinedata-distclean: cass_machinedata//$(MAKEFILE) FORCE
	cd cass_machinedata/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cass_machinedata-install_subtargets: cass_machinedata//$(MAKEFILE) FORCE
	cd cass_machinedata/ && $(MAKE) -f $(MAKEFILE) install
sub-cass_machinedata-uninstall_subtargets: cass_machinedata//$(MAKEFILE) FORCE
	cd cass_machinedata/ && $(MAKE) -f $(MAKEFILE) uninstall
cass//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) cass/ || $(MKDIR) cass/ 
	cd cass/ && $(QMAKE) cass.pro -unix -o $(MAKEFILE)
sub-cass-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) cass/ || $(MKDIR) cass/ 
	cd cass/ && $(QMAKE) cass.pro -unix -o $(MAKEFILE)
sub-cass: cass//$(MAKEFILE) FORCE
	cd cass/ && $(MAKE) -f $(MAKEFILE)
sub-cass-make_default: cass//$(MAKEFILE) FORCE
	cd cass/ && $(MAKE) -f $(MAKEFILE) 
sub-cass-make_first: cass//$(MAKEFILE) FORCE
	cd cass/ && $(MAKE) -f $(MAKEFILE) first
sub-cass-all: cass//$(MAKEFILE) FORCE
	cd cass/ && $(MAKE) -f $(MAKEFILE) all
sub-cass-clean: cass//$(MAKEFILE) FORCE
	cd cass/ && $(MAKE) -f $(MAKEFILE) clean
sub-cass-distclean: cass//$(MAKEFILE) FORCE
	cd cass/ && $(MAKE) -f $(MAKEFILE) distclean
sub-cass-install_subtargets: cass//$(MAKEFILE) FORCE
	cd cass/ && $(MAKE) -f $(MAKEFILE) install
sub-cass-uninstall_subtargets: cass//$(MAKEFILE) FORCE
	cd cass/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: cass.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile cass.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile cass.pro

qmake_all: sub-cass_remi-qmake_all sub-cass_vmi-qmake_all sub-cass_pnccd-qmake_all sub-cass_machinedata-qmake_all sub-cass-qmake_all FORCE

make_default: sub-cass_remi-make_default sub-cass_vmi-make_default sub-cass_pnccd-make_default sub-cass_machinedata-make_default sub-cass-make_default FORCE
make_first: sub-cass_remi-make_first sub-cass_vmi-make_first sub-cass_pnccd-make_first sub-cass_machinedata-make_first sub-cass-make_first FORCE
all: sub-cass_remi-all sub-cass_vmi-all sub-cass_pnccd-all sub-cass_machinedata-all sub-cass-all FORCE
clean: sub-cass_remi-clean sub-cass_vmi-clean sub-cass_pnccd-clean sub-cass_machinedata-clean sub-cass-clean FORCE
distclean: sub-cass_remi-distclean sub-cass_vmi-distclean sub-cass_pnccd-distclean sub-cass_machinedata-distclean sub-cass-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-cass_remi-install_subtargets sub-cass_vmi-install_subtargets sub-cass_pnccd-install_subtargets sub-cass_machinedata-install_subtargets sub-cass-install_subtargets FORCE
uninstall_subtargets: sub-cass_remi-uninstall_subtargets sub-cass_vmi-uninstall_subtargets sub-cass_pnccd-uninstall_subtargets sub-cass_machinedata-uninstall_subtargets sub-cass-uninstall_subtargets FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

