#ifndef CASS_MACHINE_GLOBAL_H
#define CASS_MACHINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CASS_MACHINEDATA_LIBRARY)
#  define CASS_MACHINEDATASHARED_EXPORT Q_DECL_EXPORT
#else
#  define CASS_MACHINEDATASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CASS_MACHINE_GLOBAL_H
