#ifndef CASS_PNCCD_GLOBAL_H
#define CASS_PNCCD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CASS_PNCCD_LIBRARY)
#  define CASS_PNCCDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CASS_PNCCDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CASS_PNCCD_GLOBAL_H
